In [69]:
import pandas as pd
#% pip install xlrd

# Especifica la ruta de tu archivo Excel
ruta_excel = "C:/Users/jpcan/OneDrive/Documentos/Andes Universidad/Analitica computacional/Proyecto 2/Copia de default of credit card clients.xls"

# Lee el archivo Excel en un DataFrame de pandas
datos_excel = pd.read_excel(ruta_excel, sheet_name="Data")

datos_excel.columns = datos_excel.iloc[0]

# Elimina la primera fila, ya que ahora son los nombres de las columnas
datos_excel = datos_excel[1:]


import pandas as pd

# Supongamos que 'df' es tu DataFrame
# df = pd.read_excel("ruta/a/tu/archivo.xlsx")

# Verifica si hay valores faltantes en cada columna
valores_faltantes_por_columna = datos_excel.isna().sum()

# También puedes usar df.isnull().sum() para el mismo propósito

import pandas as pd

# Supongamos que 'datos_excel' es tu DataFrame
# datos_excel = pd.read_excel("ruta/a/tu/archivo.xlsx")

# Eliminar filas con valores atípicos en la columna "EDUCATION"
datos_excel = datos_excel[datos_excel['EDUCATION'].isin([1, 2, 3, 4])]

# Eliminar filas con valores atípicos en la columna "MARRIAGE"
datos_excel = datos_excel[datos_excel['MARRIAGE'].isin([1, 2, 3])]

# Reindexar el DataFrame si es necesario
datos_excel.reset_index(drop=True, inplace=True)

# Cambiar el nombre de la columna "PAY_0" a "PAY_1"
datos_excel = datos_excel.rename(columns={"PAY_0": "PAY_1"})

# Convertir todas las columnas a tipos de datos numéricos
datos_excel = datos_excel.apply(pd.to_numeric, errors='coerce')


datos_excel.head()


0  ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_1  PAY_2  PAY_3  PAY_4  \
0   1      20000    2          2         1   24      2      2     -1     -1   
1   2     120000    2          2         2   26     -1      2      0      0   
2   3      90000    2          2         2   34      0      0      0      0   
3   4      50000    2          2         1   37      0      0      0      0   
4   5      50000    1          2         1   57     -1      0     -1      0   

0  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0  ...          0          0          0         0       689         0   
1  ...       3272       3455       3261         0      1000      1000   
2  ...      14331      14948      15549      1518      1500      1000   
3  ...      28314      28959      29547      2000      2019      1200   
4  ...      20940      19146      19131      2000     36681     10000   

0  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
0         0         0         0                           1  
1      1000         0      2000                           1  
2      1000      1000      5000                           0  
3      1100      1069      1000                           0  
4      9000       689       679                           0  

[5 rows x 25 columns]

In [81]:
# Importar las librerías necesarias
import tensorflow as tf
import numpy as np
from tensorflow import keras
#import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
#from keras.models import Sequential
#from keras.layers import Dense
#from keras.callbacks import EarlyStopping


from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [82]:
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [83]:
# split into X and Y
Y = datos_excel['default payment next month']
X = datos_excel.drop(['default payment next month'], axis=1)

print(X.shape)
print(Y.shape)

# convert to numpy arrays
X = np.array(X)

(29601, 24)
(29601,)


In [85]:
# Dividir los datos en conjuntos de entrenamiento y prueba
X_train_full, X_test, y_train_full, y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42)
X_train, X_valid, y_train, y_valid = train_test_split(
    X_train_full, y_train_full, test_size=0.2, random_state=42)

# Escalar los datos (opcional, pero es común en redes neuronales)
std_scl = StandardScaler()
std_scl.fit(X_train)

print(X_train[0:3,])
X_train = std_scl.transform(X_train)
print(X_train[0:3,])
X_valid = std_scl.transform(X_valid)
X_test = std_scl.transform(X_test)



[[ 18062 150000      1      2      1     31      0      0     -1     -1
       0      0  64276  64226   4254 145578 148012 126848   3500   4508
  145578   5115  10000   7598]
 [ 12085  60000      1      1      2     27      0      0      0      0
       0      2  21387  22416  23444  26038  28607  27997   1378   1406
    3000   3000      0    923]
 [ 11593 260000      2      1      2     27     -1     -1     -1     -1
       0     -1    399    399    399    798    399    399    399    399
     798      0    399    399]]
[[ 0.35620325 -0.13554575 -1.23717033  0.25316363 -1.06975026 -0.48887123
   0.00830747  0.1028126  -0.69989757 -0.66575939  0.22336415  0.24280027
   0.1767551   0.21388414 -0.6142591   1.58598146  1.76754819  1.47967336
  -0.12992872 -0.06039584  7.80872378  0.01615083  0.34452676  0.14494164]
 [-0.33253274 -0.82883215 -1.23717033 -1.15450643  0.86120247 -0.92366825
   0.00830747  0.1028126   0.1281084   0.18348618  0.22336415  1.97100179
  -0.4066762  -0.37597319 -0.

In [107]:
tf.random.set_seed(42)
tf.keras.backend.clear_session()

model = tf.keras.Sequential()
model.add(tf.keras.layers.InputLayer(input_shape=(24,)))
model.add(tf.keras.layers.Dense(64, activation="relu"))
model.add(tf.keras.layers.Dense(32, activation="relu"))
model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 64)                1600      
                                                                 
 dense_1 (Dense)             (None, 32)                2080      
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                                 
Total params: 3713 (14.50 KB)
Trainable params: 3713 (14.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [87]:
hidden1 = model.layers[0]
hidden1.name

'dense'

In [88]:
weights, biases = hidden1.get_weights()
weights

array([[ 0.08813706, -0.2636089 ,  0.1825119 , -0.00305492, -0.17238706,
        -0.26064277, -0.25012302,  0.10656729, -0.17226675, -0.16254736,
         0.01563627, -0.2362585 , -0.10438813, -0.1767099 , -0.18801293,
        -0.11694467,  0.09348616,  0.136184  , -0.06484352, -0.03931451,
        -0.18672603,  0.10122499, -0.10440676, -0.22930497,  0.10183689,
         0.11778006, -0.04746386,  0.20467013,  0.01819572, -0.11036216,
        -0.08593625, -0.16442978, -0.08668503, -0.2541436 , -0.18666172,
         0.21614617, -0.2887984 ,  0.08934784, -0.14401397, -0.02600083,
        -0.08619651,  0.22523564, -0.07596877,  0.05167368,  0.25418484,
        -0.054766  , -0.26704448, -0.2684912 , -0.2628836 ,  0.23198646,
         0.01163778, -0.1215158 ,  0.2895074 ,  0.18927452,  0.2860852 ,
         0.29526645, -0.08588596,  0.24282545,  0.29438603,  0.07444873,
        -0.10503253, -0.1733979 ,  0.24615782, -0.23683329],
       [ 0.09223759,  0.26686752, -0.16195622,  0.07405901,  0.

In [89]:
weights.shape

(4, 64)

In [90]:
biases

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [108]:
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=["accuracy"])

In [95]:
tf.keras.utils.plot_model(model, show_shapes=True)

You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) for plot_model to work.


In [109]:
history = model.fit(X_train, y_train, epochs=1000,
                    validation_data=(X_valid, y_valid))

Epoch 1/1000


TypeError: in user code:


    TypeError: outer_factory.<locals>.inner_factory.<locals>.tf__train_function() missing 1 required positional argument: 'steps_per_execution'


In [ ]:
import matplotlib.pyplot as plt
history_dict = history.history
# Learning curve(Loss)
# let's see the training and validation loss by epoch

# loss
loss_values = history_dict['loss'] # you can change this
val_loss_values = history_dict['val_loss'] # you can also change this

# range of X (no. of epochs)
epochs = range(1, len(loss_values) + 1) 

# plot
plt.plot(epochs, loss_values, 'bo', label='Training loss')
plt.plot(epochs, val_loss_values, 'orange', label='Validation loss')
plt.title('Training and validation loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.show()

In [ ]:
# Learning curve(accuracy)
# let's see the training and validation accuracy by epoch

# accuracy
acc = history.history['accuracy']
val_acc = history.history['val_accuracy']

# range of X (no. of epochs)
epochs = range(1, len(acc) + 1)

# plot
# "bo" is for "blue dot"
plt.plot(epochs, acc, 'bo', label='Training accuracy')
# orange is for "orange"
plt.plot(epochs, val_acc, 'orange', label='Validation accuracy')
plt.title('Training and validation accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.show()

# this is the max value - should correspond to
# the HIGHEST train accuracy
np.max(val_acc)

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

# see how these are numbers between 0 and 1? 
model.predict(X) # prob of successes (survival)
np.round(model.predict(X),0) # 1 and 0 (survival or not)
Y # 1 and 0 (survival or not)

# so we need to round to a whole number (0 or 1),
# or the confusion matrix won't work!
preds = np.round(model.predict(X),0)

# confusion matrix
print(confusion_matrix(Y, preds)) # order matters! (actual, predicted)

## array([[490,  59],   ([[TN, FP],
##       [105, 235]])     [Fn, TP]])

print(classification_report(Y, preds))
##               precision    recall  f1-score   support
## 
##            0       0.82      0.89      0.86       549
##            1       0.80      0.69      0.74       340
## 
##     accuracy                           0.82       889
##    macro avg       0.81      0.79      0.80       889
## weighted avg       0.81      0.82      0.81       889

In [49]:


# Definir el modelo de red neuronal
model = Sequential([
    Dense(64, input_shape=(X_train.shape[1],), activation='relu'),  # Capa de entrada con 64 neuronas y activación ReLU
    Dense(32, activation='relu'),  # Segunda capa con 32 neuronas y activación ReLU
    Dense(1, activation='sigmoid')  # Capa de salida con 1 neurona y activación Sigmoide para clasificación binaria
])

# Compilar el modelo
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Configurar EarlyStopping para evitar el sobreajuste
early_stopping = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

# Entrenar el modelo
history = model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=100, batch_size=32, callbacks=[early_stopping])

# Evaluar el modelo
loss, accuracy = model.evaluate(X_test, y_test)
print("Test Loss:", loss)
print("Test Accuracy:", accuracy)



Epoch 1/100


TypeError: in user code:


    TypeError: outer_factory.<locals>.inner_factory.<locals>.tf__train_function() missing 1 required positional argument: 'steps_per_execution'
